config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'products#index'

  resources :infos

  namespace :admin do
    resources :products
    resources :infos
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end

  resources :products do
    member do
      post :add_to_cart
    end
  end

  resources :carts do
    collection do
      post 'checkout'
      delete 'clean'
    end

    resources :items, controller: 'cart_items'
  end

  resources :orders do
    member do
      get :pay_with_credit_card
      post :allpay_notify
    end
  end

  namespace :account do 
    resources :orders
  end

end

app/models/info.rb
class Info < ActiveRecord::Base
end

app/controllers/admin/infos_controller.rb
class Admin::InfosController < ApplicationController
  layout "admin"

  before_action :authenticate_user!
  before_action :admin_required

  def index
    #@infos = Info.all
    @infos = Info.order("ordinal ASC")
  end

  #def show
  #  @info = Info.find(params[:id])
  #end

  def new
    @info = Info.new
    #@photo = @info.photos.new
  end

  def create
    @info = Info.new(info_params)

    if @info.save
      redirect_to admin_infos_path(@info), notice: "新增資訊成功！"
    else
      render :new
    end
  end

  def edit
    @info = Info.find(params[:id])
    #@info = Info.find(params[:info_id])
    #@info = Info.find(1)
  end

  def update
    @info = Info.find(params[:id])

    if @info.update(info_params)
      redirect_to admin_infos_path(@info), notice: "修改資訊成功！"
    else
      render :edit
    end
  end

  def destroy
    @info = Info.find(params[:id])
    @info.destroy
    redirect_to admin_infos_path(@info), notice: "資訊已刪除！"
  end

  private

  def info_params
    params.require(:info).permit(:title, :description, :ordinal)
  end

end

app/controllers/infos_controller.rb
class InfosController < ApplicationController

  def show
    @infos = Info.all
    @info = Info.find(params[:id])
  end

end

app/helpers/admin/infos_helper.rb
module Admin::InfosHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/views/admin/infos/edit.html.erb
<h2> 修改資訊 </h2>
<%= simple_form_for [:admin, @info] do |f| %>
  <div class="form-group">
    <%= f.input :title, label: "標題"  %>

    <%= f.input :description, label: "敘述"  %>

    <%= f.input :ordinal, label: "排序"  %>

  </div>

  <%= f.submit "Submit", data: { disable_width: "Submitting..." } %>

<% end %>

app/views/admin/infos/index.html.erb
<div class="col-md-12">
  <div class="group">
    <%= link_to("新增資訊", new_admin_info_path, class: "btn btn-primary pull-right") %>
  </div>

  <table class="table table-bordered">
    <thead>
      <tr>
        <td>#</td>
        <td>Title</td>
        <td>Description</td>
        <td>Ordinal</td>
        <td>Operation</td>
      </tr>
    </thead>
    <tbody>
      <% @infos.each do |info| %>
        <tr>
          <td><%= info.id %></td>
          <td><%= link_to(truncate(info.title, length: 15), info_path(info)) %></td>
          <td width="50%"><%= info.description %></td>
          <td><%= info.ordinal %></td>
          <td>
              <%= link_to("Edit", edit_admin_info_path(info), class: "btn btn-sm btn-default")%>
              <%= link_to("Delete", admin_info_path(info), class: "btn btn-sm btn-default",
                          method: :delete, data: { confirm: "Are you sure?" } )%>
          </td>
        </tr>
      <% end %>
    </tbody>

  </table>

</div>

app/views/admin/infos/new.html.erb
<h2> 新增資訊 </h2>
<%= simple_form_for [:admin, @info] do |f| %>
  <div class="form-group">
    <%= f.input :title, label: "標題"  %>

    <%= f.input :description, label: "敘述"  %>

    <%= f.input :ordinal, label: "排序"  %>

  </div>

  <%= f.submit "Submit", data: { disable_width: "Submitting..." } %>

<% end %>