config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'products#index'

  resources :infos

  namespace :admin do
    resources :products
    resources :infos
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end

  resources :products do
    member do
      post :add_to_cart
    end
  end

  resources :carts do
    collection do
      post 'checkout'
      delete 'clean'
    end

    resources :items, controller: 'cart_items'
  end

  resources :orders do
    member do
      get :pay_with_credit_card
      post :allpay_notify
    end
  end

  namespace :account do 
    resources :orders
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :photos
  
  accepts_nested_attributes_for :photos

  def default_photo
    photos.last
  end

end

app/controllers/admin/products_controller.rb
#class Admin::ProductsController < ApplicationController
#  layout "admin"

#  before_action :authenticate_user!
#  before_action :admin_required

class Admin::ProductsController < AdminController
  def index
    #@products = Product.all
    @products = Product.order("id DESC")
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
    @photo = @product.photos.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      redirect_to admin_products_path(@product), notice: "新增產品成功！"
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    #@product = Product.find(params[:product_id])
    #@product = Product.find(1)
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to admin_products_path(@product), notice: "修改產品成功！"
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to admin_products_path(@product), notice: "產品已刪除！"
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :quantity, :price, photos_attributes: [:image])
  end




end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  #before_action :authenticate_user!

  def index
    #@products = Product.all
    @products = Product.order("id DESC")
    @infos = Info.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
    @product = Product.find(params[:id])
    #current_cart.add_product_to_cart(@product)

    if !current_cart.items.include?(@product)
      current_cart.add_product_to_cart(@product)
      flash[:notice] = "你已經成功將 #{@product.title} 加入購物車"
    else
      flash[:warning] = "你的購物車內已有此商品"
    end

    redirect_to :back
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
  def render_product_photo(photo, size = "thumb")
    if photo.present?
      image_url = photo.image.send(size).url
    else
      image_url = render_no_pic_url(size)
    end

    image_tag(image_url, class: "thumbnail")
  end

  private

  def render_no_pic_url(size)
    case size
    when :medium
      volume = "300x300"
    else
      volume = "200x200"
    end

    return "http://placehold.it/#{volume}&text=No Pic"
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/edit.html.erb
<h2> 修改產品 </h2>
<%= simple_form_for [:admin, @product] do |f| %>
  <div class="form-group">
    <%= f.input :title, label: "標題"  %>

    <%= f.input :description, label: "敘述"  %>

    <%= f.input :quantity, label: "數量"  %>

    <%= f.input :price, label: "價錢"  %>

  </div>

  <%= f.submit "Submit", data: { disable_width: "Submitting..." } %>

<% end %>

app/views/admin/products/index.html.erb
<div class="col-md-12">
  <div class="group">
    <%= link_to("新增產品", new_admin_product_path, class: "btn btn-primary pull-right") %>
  </div>

  <table class="table table-bordered">
    <thead>
      <tr>
        <td>#</td>
        <td>Title</td>
        <td>Image</td>
        <td>Description</td>
        <td>Quantity</td>
        <td>Price</td>
        <td>Operation</td>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.id %></td>
          <td><%= render_product_photo(product.default_photo) %></td>
          <td><%= link_to(truncate(product.title, length: 15), admin_product_path(product)) %></td>
          <td><%= product.description %></td>
          <td><%= product.quantity %></td>
          <td><%= product.price %></td>
          <td>
              <%= link_to("Edit", edit_admin_product_path(product), class: "btn btn-sm btn-default")%>
              <%= link_to("Delete", admin_product_path(product), class: "btn btn-sm btn-default",
                          method: :delete, data: { confirm: "Are you sure?" } )%>
          </td>
        </tr>
      <% end %>
    </tbody>

  </table>

</div>

<!--
<ul>
  <% @products.each do |product| %>

    <li> <%= link_to(product.title, admin_product_path(product)) %> </li>
  <% end %>
</ul>
-->

app/views/admin/products/new.html.erb
<h2> 新增產品 </h2>
<%= simple_form_for [:admin, @product] do |f| %>
  <div class="form-group">
    <%= f.input :title, label: "標題"  %>

    <%= f.input :description, label: "敘述"  %>

    <%= f.input :quantity, label: "數量"  %>

    <%= f.input :price, label: "價錢"  %>

    <%= f.simple_fields_for :photos do |c| %>
      <%= c.input :image, as: :file %>
    <% end %>
  </div>

  <%= f.submit "Submit", data: { disable_width: "Submitting..." } %>

<% end %>

app/views/admin/products/show.html.erb
<div class="row">
  <div class="col-md-5">
    <%= render_product_photo(@product.default_photo, :medium) %>
  </div>

  <div class="col-md-7">
    <h2> <%= @product.title %> </h2>

    <div style="height:100px;">
      <p>
        <%= @product.description %>
      </p>
    </div>

    <div> 數量 : <%= @product.quantity %> </div>

    <div class="product-price"> $ <%= @product.price %> </div>

    <div class="pull-right">
      <%= link_to("加入購物車", "#", :class => "btn btn-primary btn-lg btn-danger") %>
    </div>
  </div>
</div>