config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'products#index'

  resources :infos

  namespace :admin do
    resources :products
    resources :infos
    resources :orders do
      member do
        post :cancel
        post :ship
        post :shipped
        post :return
      end
    end
  end

  resources :products do
    member do
      post :add_to_cart
    end
  end

  resources :carts do
    collection do
      post 'checkout'
      delete 'clean'
    end

    resources :items, controller: 'cart_items'
  end

  resources :orders do
    member do
      get :pay_with_credit_card
      post :allpay_notify
    end
  end

  namespace :account do 
    resources :orders
  end

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :cart_items, dependent: :destroy
  has_many :items, through: :cart_items, source: :product

  def find_cart_item(product)
    cart_items.find_by(product_id: product)
  end

  def add_product_to_cart(product)
    items << product
  end

  def total_price
    #cart_items.inject(0) {|sum, item| sum + (item.product.price * item.quantity) }
    sum = 0
    cart_items.each do |item|
      sum = sum + item.product.price * item.quantity
    end

    return sum
  end

  def clean!
    cart_items.destroy_all
  end

end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
  belongs_to :cart
  belongs_to :product

end

app/models/info.rb
class Info < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base


  belongs_to :user
  has_many :items, :class_name => "OrderItem", :dependent => :destroy
  has_one :info, class_name: "OrderInfo", dependent: :destroy

  accepts_nested_attributes_for :info

  scope :recent, -> { order("id DESC") }

  def build_item_cache_from_cart(cart)
    cart.items.each do |cart_item|
      item = items.build
      item.product_name = cart_item.title
      #item.quantity = cart_items.find_by(product_id: cart_item).quantity
      item.quantity = cart.find_cart_item(cart_item).quantity
      item.price = cart_item.price
      item.save
    end
  end


  def calculate_total!(cart)
    self.total = cart.total_price
    self.save
  end

#  before_create :generate_token

#  def generate_token
#    self.token = SecureRandom.uuid
#  end
include Tokenable

  def paid?
    is_paid
  end


  def set_payment_with!(method)
    self.update_column(:payment_method, method )
  end

  def pay!
    self.update_column(:is_paid, true )
  end


  include AASM
 
  aasm do
    state :order_placed, initial: true
    state :paid
    state :shipping
    state :shipped
    state :order_cancelled
    state :good_returned
 
 
    event :make_payment do
      transitions from: :order_placed, to: :paid
    end
 
    event :ship do
      transitions from: :paid,         to: :shipping
    end
 
    event :deliver do
      transitions from: :shipping,     to: :shipped
    end
 
    event :return_good do
      transitions from: :shipped,      to: :good_returned
    end
 
    event :cancel_order do
      transitions from: [:order_placed, :paid], to: :order_cancelled
    end
  end
end

app/models/order_info.rb
class OrderInfo < ActiveRecord::Base
  belongs_to :order

  validates :billing_name, presence: true
  validates :billing_address, presence: true
  validates :shipping_name, presence: true
  validates :shipping_name, presence: true

end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
end

app/models/photo.rb
class Photo < ActiveRecord::Base

  belongs_to :product

  mount_uploader :image, ImageUploader

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :photos
  
  accepts_nested_attributes_for :photos

  def default_photo
    photos.last
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders  

  def admin?
    is_admin
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout "admin"

  before_action :authenticate_user!
  before_action :admin_required
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!, only: [:checkout]

  def checkout
    @order = current_user.orders.build
    @info = @order.build_info
  end

  def clean
    current_cart.clean!
    flash[:warning] = "已清空購物車"
    redirect_to carts_path
  end
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController

  def show
    @infos = Info.all
    @info = Info.find(params[:id])
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!, except: :allpay_notify
 
  protect_from_forgery except: :allpay_notify

  def allpay_notify
    order = Order.find_by_token(params[:id])
    type = params[:type]

    if params[:RtnCode] == "1"
      order.set_payment_with!(type)
      order.make_payment!
    end

    render text: '1|OK', status: 200
  end

  def create
    @order = current_user.orders.build(order_params)
 
    if @order.save
#      @order.build_item_cache_from_cart(current_cart)
#      @order.calculate_total!(current_cart)
#      current_cart.cart_items.destroy_all
      OrderPlacingService.new(current_cart, @order).place_order!
      redirect_to order_path(@order.token)
    else
      render "carts/checkout"
    end
  end


  def show
    @order = Order.find_by_token(params[:id])
    @order_info = @order.info
    @order_items = @order.items
  end

  def pay_with_credit_card
    @order = Order.find_by_token(params[:id])
    @order.set_payment_with!("credit_card")

    @order.make_payment!

    #current_cart.clean!
    #redirect_to "/", :notice => "成功完成付款"
    redirect_to account_orders_path, :notice => "成功完成付款"
  end
 
  private
 
  def order_params
    params.require(:order).permit(:info_attributes => [:billing_name, :billing_address,:shipping_name, :shipping_address] )
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  #before_action :authenticate_user!

  def index
    #@products = Product.all
    @products = Product.order("id DESC")
    @infos = Info.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
    @product = Product.find(params[:id])
    #current_cart.add_product_to_cart(@product)

    if !current_cart.items.include?(@product)
      current_cart.add_product_to_cart(@product)
      flash[:notice] = "你已經成功將 #{@product.title} 加入購物車"
    else
      flash[:warning] = "你的購物車內已有此商品"
    end

    redirect_to :back
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def notice_message
    alert_types = { notice: :success, alert: :danger }

    close_button_options = { class: "close", "data-dismiss" => "alert", "aria-hidden" => true }
    close_button = content_tag(:button, "×", close_button_options)

    alerts = flash.map do |type, message|
      alert_content = close_button + message

      alert_type = alert_types[type.to_sym] || type
      alert_class = "alert alert-#{alert_type} alert-dismissable"

      content_tag(:div, alert_content, class: alert_class)
    end

    alerts.join("\n").html_safe
  end

  def render_cart_items_count(cart)
    cart.cart_items.count
  end

end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
  def render_cart_total_price(cart)
    cart.total_price
  end
  
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/helpers/orders_helper.rb
module OrdersHelper

  def render_order_timestamp(order)
    order.created_at.to_s(:long)
  end

  def render_order_state(order)
    t("orders.order_state.#{order.aasm_state}")
  end
  
  def render_order_paid_state(order)
    if order.paid?
      "已付款"
    else
      "未付款"
    end
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/common/_footer.html.erb
<div class="container" style="margin-top: 100px;">

  <footer>
    <div class="row">
      <div class="col-lg-12">
        <p class="text-center">
          Copyright ©2015 ToolStore <br>
          Design by <a href="https://github.com/rugbyball" target=_new>James</a>
        </p>
      </div>
    </div>
  </footer>

</div>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Tool Store</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if current_user %>
        <!--
        <ul class="nav navbar-nav">
          <li class="active">
            <%= link_to("Products", admin_products_path) %>
          </li>
        </ul>
        -->
      <% end %>

      <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to carts_path do  %>
              購物車 <i class="fa fa-shopping-cart"> </i> (<%= render_cart_items_count(current_cart) %>)
            <% end %>
          </li>

          <% if !current_user %>
            <li> <%= link_to("註冊", new_user_registration_path) %> </li>
            <li> <%= link_to("登入", new_user_session_path) %> </li>
          <% else %>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Hi!, <%= current_user.email %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <% if current_user.admin? %>
                <li> 
                  <%= link_to("Admin 選單", admin_products_path ) %>
                </li>
              <% end %>
              <li> <%= link_to("個人訂單列表", account_orders_path ) %> </li>
              <li> <%= link_to("帳號設定", edit_user_registration_path) %> </li>
              <li> <%= link_to("登出", destroy_user_session_path, method: :delete) %> </li>
            </ul>
          </li>
          <% end %> 
          <%= render "common/share" %>
      </ul>
    </div>
  </div>
</nav>

app/views/common/_share.html.erb
<li>
  <a href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Fec2-54-64-151-0.ap-northeast-1.compute.amazonaws.com%3A3000%2F&t=ToolStore" title="Share on Facebook" target="_blank">
    <!--<img src="images/social_flat_rounded_rects_svg/Facebook.svg">-->
    <%= image_tag "Facebook.svg", size: "20x20" %>
  </a>
</li>
<li>
  <a href="https://twitter.com/intent/tweet?source=http%3A%2F%2Fec2-54-64-151-0.ap-northeast-1.compute.amazonaws.com%3A3000%2F&text=ToolStore:%20http%3A%2F%2Fec2-54-64-151-0.ap-northeast-1.compute.amazonaws.com%3A3000%2F" target="_blank" title="Tweet">
    <!--<img src="images/social_flat_rounded_rects_svg/Twitter.svg">-->
    <%= image_tag "Twitter.svg", size: "20x20" %>
  </a>
</li>

app/views/common/_site_item.html.erb
    <div class="col-md-3">
      <p class="lead">關於 ToolStore</p>
      <div class="list-group">
        <!--
        <a href="#" class="list-group-item">產品介紹</a>
        <a href="#" class="list-group-item">哪裡買</a>
        <a href="#" class="list-group-item">聯絡我們</a>
        -->
        <% @infos.each do |info| %>
          <!--<a href="#" class="list-group-item"><%= info.title %></a>-->
          <%= link_to(info.title, info_path(info), class: "list-group-item") %>
        <% end %>
      </div>
    </div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Artstore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <%= render "common/navbar" %>
    <%= notice_message %>
    
    <div class="row">
      <!--
      <div class="col-md-2">
        <ul class="nav nav-pills nav-stacked" style="max-width: 300px;">          
          <li> <%= link_to("Products", admin_products_path) %> </li>
          <li> <%= link_to("Orders", admin_orders_path) %> </li>
        </ul>
      </div>
      -->
      <div class="col-md-3">
        <div class="list-group">
          <p class="lead">後台管理</p>
          <%= link_to("產品管理", admin_products_path, class: 'list-group-item') %>
          <%= link_to("訂單維護", admin_orders_path, class: 'list-group-item') %>
          <%= link_to("網站資訊維護", admin_infos_path, class: 'list-group-item') %>
        </div>
      </div>      

      <div class="col-md-9">

        <%= yield %>
      </div>
      
    </div>





  </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToolStore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "common/navbar" %>
<%= notice_message %>
<%= yield %>
<%= render "common/footer" %>

</body>
</html>